### PR TITLE
Update deepin-wine5

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by taotieren** [comment]
KDE 桌面需要手动运行一下
```bash
/opt/deepinwine/apps/Deepin-QQ/run.sh -d
```

**Comment by taotieren** [comment]
PCQQ 已更新至 `9.4.1`

**Comment by taotieren** [comment]
重新打包后在 Arch Linux 上测试暂时没有上述问题，

```bash
uname -a         
Linux archlinux 5.4.85-1-lts #1 SMP Mon, 21 Dec 2020 19:28:35 +0000 x86_64 GNU/Linux

```

**Comment by taotieren** [comment]
编译好的包

https://github.com/taotieren/deepin-wine-qq-arch/releases

**Comment by zw963** [comment]
不工作啊。

```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  deepin-wine-qq-9.4.0.27525-1

  1 deepin-wine-qq                           (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): deepin-wine-qq
  1 deepin-wine-qq                           (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: deepin-wine-qq
==> Making package: deepin-wine-qq 9.4.0.27525-1 (Sat 26 Dec 2020 12:50:01 AM CST)
==> Retrieving sources...
  -> Downloading deepin.com.qq.im_9.1.8deepin0_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
==> ERROR: Failure while downloading https://ftp.sjtu.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/deepin.com.qq.im_9.1.8deepin0_i386.deb
    Aborting...
error downloading sources: deepin-wine-qq

```

**Comment by taotieren** [comment]
用我仓库 master 分支的包昨天升级 deepinqqver  2020年12月26日 00:52，"Billy.Zheng" <notifications@github.com>写道：

不工作啊。

:: Checking for conflicts...

:: Checking for inner conflicts...

[Aur:1]  deepin-wine-qq-9.4.0.27525-1



  1 deepin-wine-qq                           (Installed) (Build Files Exist)

==> Packages to cleanBuild?

==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)

==> 

:: PKGBUILD up to date, Skipping (1/1): deepin-wine-qq

  1 deepin-wine-qq                           (Installed) (Build Files Exist)

==> Diffs to show?

==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)

==> 

:: (1/1) Parsing SRCINFO: deepin-wine-qq

==> Making package: deepin-wine-qq 9.4.0.27525-1 (Sat 26 Dec 2020 12:50:01 AM CST)

==> Retrieving sources...

  -> Downloading deepin.com.qq.im_9.1.8deepin0_i386.deb...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (22) The requested URL returned error: 404 

==> ERROR: Failure while downloading https://ftp.sjtu.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/deepin.com.qq.im_9.1.8deepin0_i386.deb

    Aborting...

error downloading sources: deepin-wine-qq

**Comment by taotieren** [comment]
> 不工作啊。
> 
> ```
> :: Checking for conflicts...
> :: Checking for inner conflicts...
> [Aur:1]  deepin-wine-qq-9.4.0.27525-1
> 
>   1 deepin-wine-qq                           (Installed) (Build Files Exist)
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> 
> :: PKGBUILD up to date, Skipping (1/1): deepin-wine-qq
>   1 deepin-wine-qq                           (Installed) (Build Files Exist)
> ==> Diffs to show?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> 
> :: (1/1) Parsing SRCINFO: deepin-wine-qq
> ==> Making package: deepin-wine-qq 9.4.0.27525-1 (Sat 26 Dec 2020 12:50:01 AM CST)
> ==> Retrieving sources...
>   -> Downloading deepin.com.qq.im_9.1.8deepin0_i386.deb...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404 
> ==> ERROR: Failure while downloading https://ftp.sjtu.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/deepin.com.qq.im_9.1.8deepin0_i386.deb
>     Aborting...
> error downloading sources: deepin-wine-qq
> ```

https://github.com/countstarlight/deepin-wine-qq-arch/pull/33

**Pull request closed without merging**
